# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Omid\Desktop\SIO179NitrateCalc.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(786, 399)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 20, 391, 331))
        self.tabWidget.setObjectName("tabWidget")
        self.tabFile = QtWidgets.QWidget()
        self.tabFile.setObjectName("tabFile")
        self.lineEdit = QtWidgets.QLineEdit(self.tabFile)
        self.lineEdit.setGeometry(QtCore.QRect(20, 40, 231, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.tabFile)
        self.pushButton.setGeometry(QtCore.QRect(260, 40, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.spinBox = QtWidgets.QSpinBox(self.tabFile)
        self.spinBox.setGeometry(QtCore.QRect(160, 100, 42, 22))
        self.spinBox.setObjectName("spinBox")
        self.spinBox_2 = QtWidgets.QSpinBox(self.tabFile)
        self.spinBox_2.setGeometry(QtCore.QRect(160, 130, 42, 22))
        self.spinBox_2.setObjectName("spinBox_2")
        self.spinBox_3 = QtWidgets.QSpinBox(self.tabFile)
        self.spinBox_3.setGeometry(QtCore.QRect(160, 160, 42, 22))
        self.spinBox_3.setObjectName("spinBox_3")
        self.spinBox_4 = QtWidgets.QSpinBox(self.tabFile)
        self.spinBox_4.setGeometry(QtCore.QRect(160, 190, 42, 22))
        self.spinBox_4.setObjectName("spinBox_4")
        self.spinBox_5 = QtWidgets.QSpinBox(self.tabFile)
        self.spinBox_5.setGeometry(QtCore.QRect(160, 220, 42, 22))
        self.spinBox_5.setObjectName("spinBox_5")
        self.label = QtWidgets.QLabel(self.tabFile)
        self.label.setGeometry(QtCore.QRect(130, 80, 131, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tabFile)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 61, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tabFile)
        self.label_3.setGeometry(QtCore.QRect(20, 130, 81, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tabFile)
        self.label_4.setGeometry(QtCore.QRect(20, 160, 101, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tabFile)
        self.label_5.setGeometry(QtCore.QRect(20, 190, 111, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tabFile)
        self.label_6.setGeometry(QtCore.QRect(20, 220, 111, 16))
        self.label_6.setObjectName("label_6")
        self.pushButton_2 = QtWidgets.QPushButton(self.tabFile)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 260, 301, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.tabWidget.addTab(self.tabFile, "")
        self.tabSpec = QtWidgets.QWidget()
        self.tabSpec.setObjectName("tabSpec")
        self.cmbIntensityVariableSelector = QtWidgets.QComboBox(self.tabSpec)
        self.cmbIntensityVariableSelector.setGeometry(QtCore.QRect(20, 30, 151, 22))
        self.cmbIntensityVariableSelector.setObjectName("cmbIntensityVariableSelector")
        self.cmbIntensityVariableSelector.addItem("")
        self.cmbIntensityVariableSelector.addItem("")
        self.cmbIntensityVariableSelector.addItem("")
        self.cmbIntensityVariableSelector.addItem("")
        self.cmbIntensityVariableSelector.addItem("")
        self.pushButton_3 = QtWidgets.QPushButton(self.tabSpec)
        self.pushButton_3.setGeometry(QtCore.QRect(274, 30, 101, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.tabWidget.addTab(self.tabSpec, "")
        self.tabSali = QtWidgets.QWidget()
        self.tabSali.setObjectName("tabSali")
        self.tabWidget.addTab(self.tabSali, "")
        self.tabTemp = QtWidgets.QWidget()
        self.tabTemp.setObjectName("tabTemp")
        self.tabWidget.addTab(self.tabTemp, "")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(440, 20, 321, 331))
        self.frame.setAutoFillBackground(False)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.frame)
        self.doubleSpinBox.setGeometry(QtCore.QRect(80, 30, 62, 22))
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.frame)
        self.doubleSpinBox_2.setGeometry(QtCore.QRect(80, 70, 62, 22))
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.frame)
        self.doubleSpinBox_3.setGeometry(QtCore.QRect(80, 110, 62, 22))
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.frame)
        self.doubleSpinBox_4.setGeometry(QtCore.QRect(80, 150, 62, 22))
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.spinBox_6 = QtWidgets.QSpinBox(self.frame)
        self.spinBox_6.setGeometry(QtCore.QRect(80, 190, 61, 22))
        self.spinBox_6.setObjectName("spinBox_6")
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.frame)
        self.doubleSpinBox_5.setGeometry(QtCore.QRect(220, 30, 62, 22))
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(self.frame)
        self.doubleSpinBox_6.setGeometry(QtCore.QRect(220, 70, 62, 22))
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.doubleSpinBox_7 = QtWidgets.QDoubleSpinBox(self.frame)
        self.doubleSpinBox_7.setGeometry(QtCore.QRect(220, 110, 62, 22))
        self.doubleSpinBox_7.setObjectName("doubleSpinBox_7")
        self.doubleSpinBox_8 = QtWidgets.QDoubleSpinBox(self.frame)
        self.doubleSpinBox_8.setGeometry(QtCore.QRect(220, 150, 62, 22))
        self.doubleSpinBox_8.setObjectName("doubleSpinBox_8")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(10, 30, 47, 14))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(10, 70, 47, 14))
        self.label_8.setObjectName("label_8")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(10, 110, 47, 14))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(10, 150, 47, 14))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(10, 190, 61, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(160, 30, 47, 14))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setGeometry(QtCore.QRect(160, 70, 47, 14))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frame)
        self.label_16.setGeometry(QtCore.QRect(160, 110, 47, 14))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frame)
        self.label_17.setGeometry(QtCore.QRect(160, 150, 47, 14))
        self.label_17.setObjectName("label_17")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(30, 280, 261, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 786, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Browse"))
        self.label.setText(_translate("MainWindow", "Column # (Zero Indexed)"))
        self.label_2.setText(_translate("MainWindow", "Dark Signal"))
        self.label_3.setText(_translate("MainWindow", "DI Water Signal"))
        self.label_4.setText(_translate("MainWindow", "Zero Nitrate Signal"))
        self.label_5.setText(_translate("MainWindow", "Known Nitrate Signal"))
        self.label_6.setText(_translate("MainWindow", "Test Sample Signal"))
        self.pushButton_2.setText(_translate("MainWindow", "Start Reading"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFile), _translate("MainWindow", "File Read"))
        self.cmbIntensityVariableSelector.setCurrentText(_translate("MainWindow", "I(Dark)"))
        self.cmbIntensityVariableSelector.setItemText(0, _translate("MainWindow", "I(Dark)"))
        self.cmbIntensityVariableSelector.setItemText(1, _translate("MainWindow", "I(Blank)"))
        self.cmbIntensityVariableSelector.setItemText(2, _translate("MainWindow", "I(KN)"))
        self.cmbIntensityVariableSelector.setItemText(3, _translate("MainWindow", "I(ZN)"))
        self.cmbIntensityVariableSelector.setItemText(4, _translate("MainWindow", "I(TS)"))
        self.pushButton_3.setText(_translate("MainWindow", "Start Reading!"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSpec), _translate("MainWindow", "Spectrometer Read"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSali), _translate("MainWindow", "Salinity Read"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTemp), _translate("MainWindow", "Temperature Read"))
        self.label_7.setText(_translate("MainWindow", "S(Norm)"))
        self.label_8.setText(_translate("MainWindow", "S(TS)"))
        self.label_11.setText(_translate("MainWindow", "S(ZN)"))
        self.label_12.setText(_translate("MainWindow", "S(KN)"))
        self.label_13.setText(_translate("MainWindow", "Path Length"))
        self.label_14.setText(_translate("MainWindow", "[NO3-]"))
        self.label_15.setText(_translate("MainWindow", "T(TS)"))
        self.label_16.setText(_translate("MainWindow", "T(ZN)"))
        self.label_17.setText(_translate("MainWindow", "T(KN)"))
        self.pushButton_4.setText(_translate("MainWindow", "Compute Nitrate Level"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

